name: Django CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3

      - name: Create env file
        run: |
            touch .env
            echo POSTGRES_DB=${{ vars.POSTGRES_DB }} >> .env
            echo POSTGRES_USER=${{ vars.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }} >> .env
            echo POSTGRES_PORT=${{ vars.POSTGRES_PORT }} >> .env

            echo PGADMIN_DEFAULT_EMAIL=${{ vars.PGADMIN_DEFAULT_EMAIL }} >> .env
            echo PGADMIN_DEFAULT_PASSWORD=${{ vars.PGADMIN_DEFAULT_PASSWORD }} >> .env

      - name: Install django server
        run: |
          make docker-build

      - name: Lint with ruff
        run: |
          make ruff